import {
  Home,
  Scan,
  Copy,
  FileDigit,
  Clock,
  FolderX,
  FileQuestion,
  Share2,
  Trash2,
  FolderTree,
  FolderSync,
  Building2,
  FileSpreadsheet,
  Tag,
  Star,
  ShieldAlert,
  Activity,
  UserX,
  BarChart3,
  FileClock,
  Leaf,
  Layers,
  Archive,
  History,
  Kanban,
  Settings,
  Info,
  Film,
  Zap,
} from 'lucide-react'
import {
  faGaugeHigh,
  faTrashCan,
  faFolderTree,
  faShieldCheck,
  faLayerGroup,
  faGear,
  faCircleInfo,
  faSparkles,
} from '@fortawesome/pro-duotone-svg-icons'

// Primary 5-Hub Navigation for Clean, Modern Navigation
export const PRIMARY_HUBS = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    icon: Home,
    faIcon: faGaugeHigh,
    description: 'Drive overview, folder explorer, and storage telemetry',
    badge: null,
  },
  {
    id: 'clean',
    label: 'Cleanup Center',
    path: '/clean',
    icon: Trash2,
    faIcon: faTrashCan,
    description: 'Smart scan, duplicates, 4K media, and trash purge',
    badge: '8 Tools',
    subTabs: [
      { id: 'smart-scan', label: 'Smart Scan' },
      { id: 'duplicates', label: 'Duplicates' },
      { id: 'large-files', label: 'Large Files' },
      { id: 'old-files', label: 'Old Files' },
      { id: 'empty-items', label: 'Empty Items' },
      { id: 'temp-files', label: 'Temporary Files' },
      { id: 'media-optimizer', label: 'Media Optimiser' },
      { id: 'trash-governance', label: 'Cloud Trash' },
    ],
  },
  {
    id: 'organise',
    label: 'Organisation Studio',
    path: '/organise',
    icon: FolderTree,
    faIcon: faFolderTree,
    description: 'Folder architect, shared drives, and taxonomy',
    badge: '5 Tools',
    subTabs: [
      { id: 'folders', label: 'Folder Explorer' },
      { id: 'reorganizer', label: 'Smart Reorganiser' },
      { id: 'shared-drives', label: 'Shared Drives' },
      { id: 'workspace', label: 'Google Workspace' },
      { id: 'labels', label: 'Drive Labels' },
    ],
  },
  {
    id: 'security',
    label: 'Security & Governance',
    path: '/security',
    icon: ShieldAlert,
    faIcon: faShieldCheck,
    description: 'Exposure audits, external sharing, and ROT',
    badge: '4 Tools',
    subTabs: [
      { id: 'audit', label: 'Security Audit' },
      { id: 'sharing', label: 'External Collaborators' },
      { id: 'rot', label: 'ROT Classification' },
      { id: 'carbon', label: 'Carbon Impact' },
    ],
  },
  {
    id: 'operations',
    label: 'Operations & Automation',
    path: '/operations',
    icon: Layers,
    faIcon: faLayerGroup,
    description: 'Bulk rules, kanban triage, triggers, and sync',
    badge: '6 Tools',
    subTabs: [
      { id: 'bulk', label: 'Bulk Actions' },
      { id: 'kanban', label: 'Kanban Triage' },
      { id: 'archive', label: 'Auto-Archive' },
      { id: 'triggers', label: 'Automation Triggers' },
      { id: 'sync', label: 'Live Sync Stream' },
      { id: 'history', label: 'Audit History' },
    ],
  },
]

// All Actionable Tools for the ⌘K Command Palette & Search
export const ALL_TOOLS = [
  // Primary Hubs
  {
    id: 'hub-dashboard',
    label: 'Dashboard Overview',
    path: '/dashboard',
    icon: Home,
    categoryTitle: 'Primary Hubs',
    description: 'Drive overview and storage telemetry gauge',
    keywords: ['home', 'root', 'overview', 'dashboard'],
  },
  {
    id: 'hub-clean',
    label: 'Cleanup Center',
    path: '/clean',
    icon: Trash2,
    categoryTitle: 'Primary Hubs',
    description: 'Unified storage hygiene, scanner, and trash hub',
    keywords: ['clean', 'hygiene', 'purge', 'storage'],
  },
  {
    id: 'hub-organise',
    label: 'Organisation Studio',
    path: '/organise',
    icon: FolderTree,
    categoryTitle: 'Primary Hubs',
    description: 'Folder hierarchy, rule architect, and shared drives',
    keywords: ['organise', 'organize', 'folders', 'structure'],
  },
  {
    id: 'hub-security',
    label: 'Security & Governance',
    path: '/security',
    icon: ShieldAlert,
    categoryTitle: 'Primary Hubs',
    description: 'Permissions audit, external exposure, and compliance',
    keywords: ['security', 'governance', 'exposure', 'audit'],
  },
  {
    id: 'hub-operations',
    label: 'Operations & Automation',
    path: '/operations',
    icon: Layers,
    categoryTitle: 'Primary Hubs',
    description: 'Batch rules, kanban board, triggers, and sync engine',
    keywords: ['operations', 'automation', 'cron', 'bulk', 'sync'],
  },

  // Cleanup Scanners (Deep links to /clean?tab=...)
  {
    id: 'tool-smart-scan',
    label: 'Smart Scan',
    path: '/clean',
    tab: 'smart-scan',
    icon: Scan,
    categoryTitle: 'Cleanup Tools',
    description: 'Comprehensive multi-analyzer hygiene & ROT scan',
    keywords: ['scan', 'analyze', 'hygiene', 'audit', 'health'],
  },
  {
    id: 'tool-duplicates',
    label: 'Duplicate Files',
    path: '/clean',
    tab: 'duplicates',
    icon: Copy,
    categoryTitle: 'Cleanup Tools',
    description: 'Find identical copies and reclaim redundant space',
    keywords: ['dupes', 'clones', 'copy', 'md5', 'redundant'],
  },
  {
    id: 'tool-large-files',
    label: 'Large Files',
    path: '/clean',
    tab: 'large-files',
    icon: FileDigit,
    categoryTitle: 'Cleanup Tools',
    description: 'Identify storage-heavy files over 100MB / 1GB',
    keywords: ['heavy', 'huge', 'size', 'storage', 'space'],
  },
  {
    id: 'tool-old-files',
    label: 'Old Files',
    path: '/clean',
    tab: 'old-files',
    icon: Clock,
    categoryTitle: 'Cleanup Tools',
    description: 'Filter untouched files older than 1 to 5+ years',
    keywords: ['stale', 'aged', 'archive', 'ancient', 'inactive'],
  },
  {
    id: 'tool-empty-items',
    label: 'Empty Items',
    path: '/clean',
    tab: 'empty-items',
    icon: FolderX,
    categoryTitle: 'Cleanup Tools',
    description: 'Prune zero-byte files and empty directory trees',
    keywords: ['zero', 'blank', 'empty folders', 'prune'],
  },
  {
    id: 'tool-temp-files',
    label: 'Temporary Files',
    path: '/clean',
    tab: 'temp-files',
    icon: FileQuestion,
    categoryTitle: 'Cleanup Tools',
    description: 'Detect orphaned cache, tmp, and log remnants',
    keywords: ['tmp', 'cache', 'scratch', 'orphan', 'junk'],
  },
  {
    id: 'tool-media-opt',
    label: 'Media Optimiser',
    path: '/clean',
    tab: 'media-optimizer',
    icon: Film,
    categoryTitle: 'Cleanup Tools',
    description: 'Compress 4K video hogs, RAW images, and bursts',
    keywords: ['photos', 'video', 'heic', '4k', 'compress'],
  },
  {
    id: 'tool-trash-gov',
    label: 'Cloud Trash',
    path: '/clean',
    tab: 'trash-governance',
    icon: Trash2,
    categoryTitle: 'Cleanup Tools',
    description: 'Permanent bin purge and auto-expiration policy',
    keywords: ['bin', 'purge', 'empty', 'delete', 'lifecycle'],
  },

  // Organisation Tools (Deep links to /organise?tab=...)
  {
    id: 'tool-folders',
    label: 'Folder Explorer',
    path: '/organise',
    tab: 'folders',
    icon: FolderTree,
    categoryTitle: 'Organisation',
    description: 'Visual folder tree explorer and hierarchy navigator',
    keywords: ['directories', 'tree', 'folders', 'structure'],
  },
  {
    id: 'tool-reorganizer',
    label: 'Smart Folder Reorganiser',
    path: '/organise',
    tab: 'reorganizer',
    icon: FolderSync,
    categoryTitle: 'Organisation',
    description: 'Smart rule-based auto-sorting into year/type folders',
    keywords: ['reorganize', 'sort', 'architect', 'archive tree'],
  },
  {
    id: 'tool-shared-drives',
    label: 'Shared Drives',
    path: '/organise',
    tab: 'shared-drives',
    icon: Building2,
    categoryTitle: 'Organisation',
    description: 'Team drive hygiene, storage quotas, and member audits',
    keywords: ['team drives', 'enterprise', 'shared drive', 'corpora'],
  },
  {
    id: 'tool-workspace',
    label: 'Google Workspace Files',
    path: '/organise',
    tab: 'workspace',
    icon: FileSpreadsheet,
    categoryTitle: 'Organisation',
    description: 'Audit Google Docs, Sheets, Slides, and Forms',
    keywords: ['docs', 'sheets', 'slides', 'forms', 'gsuite'],
  },
  {
    id: 'tool-labels',
    label: 'Drive Labels',
    path: '/organise',
    tab: 'labels',
    icon: Tag,
    categoryTitle: 'Organisation',
    description: 'Apply governance, confidentiality, and taxonomy metadata',
    keywords: ['taxonomy', 'metadata', 'retention', 'confidential'],
  },

  // Security & Governance Tools (Deep links to /security?tab=...)
  {
    id: 'tool-security-audit',
    label: 'Security Audit',
    path: '/security',
    tab: 'audit',
    icon: ShieldAlert,
    categoryTitle: 'Security & Governance',
    description: 'Exposure risk assessment, anyone-with-link scanner',
    keywords: ['security', 'exposure', 'risk', 'public links', 'audit'],
  },
  {
    id: 'tool-shared-files',
    label: 'External Collaborators',
    path: '/security',
    tab: 'sharing',
    icon: Share2,
    categoryTitle: 'Security & Governance',
    description: 'Audit external collaborator links and public shares',
    keywords: ['sharing', 'external', 'public', 'permissions'],
  },
  {
    id: 'tool-rot',
    label: 'ROT Analysis',
    path: '/security',
    tab: 'rot',
    icon: FileClock,
    categoryTitle: 'Security & Governance',
    description: 'Redundant, Obsolete, and Trivial data classification',
    keywords: ['rot', 'obsolete', 'trivial', 'redundant', 'compliance'],
  },
  {
    id: 'tool-carbon',
    label: 'Carbon Footprint',
    path: '/security',
    tab: 'carbon',
    icon: Leaf,
    categoryTitle: 'Security & Governance',
    description: 'CO2 carbon emission analytics for cloud storage',
    keywords: ['green', 'carbon', 'co2', 'emissions', 'sustainability'],
  },

  // Operations & Automation Tools (Deep links to /operations?tab=...)
  {
    id: 'tool-bulk',
    label: 'Bulk Actions',
    path: '/operations',
    tab: 'bulk',
    icon: Layers,
    categoryTitle: 'Operations & Automation',
    description: 'Batch file operations, migrations, and label tags',
    keywords: ['batch', 'multi', 'bulk', 'rules'],
  },
  {
    id: 'tool-kanban',
    label: 'Kanban Workflow',
    path: '/operations',
    tab: 'kanban',
    icon: Kanban,
    categoryTitle: 'Operations & Automation',
    description: 'Interactive triage board for file lifecycle review',
    keywords: ['board', 'triage', 'todo', 'kanban', 'cards'],
  },
  {
    id: 'tool-archive',
    label: 'Auto-Archive',
    path: '/operations',
    tab: 'archive',
    icon: Archive,
    categoryTitle: 'Operations & Automation',
    description: 'Cold storage rules and automated zip bundling',
    keywords: ['zip', 'cold storage', 'archive', 'compress'],
  },
  {
    id: 'tool-triggers',
    label: 'Automation Triggers',
    path: '/operations',
    tab: 'triggers',
    icon: Zap,
    categoryTitle: 'Operations & Automation',
    description: 'Schedule automated daily, weekly, or event-based jobs',
    keywords: ['triggers', 'cron', 'schedule', 'remnotif'],
  },
  {
    id: 'tool-sync',
    label: 'Live Sync Stream',
    path: '/operations',
    tab: 'sync',
    icon: Activity,
    categoryTitle: 'Operations & Automation',
    description: 'Live Drive Changes API delta synchronisation engine',
    keywords: ['sync', 'stream', 'delta', 'webhooks', 'api engine'],
  },
  {
    id: 'tool-history',
    label: 'Audit History',
    path: '/operations',
    tab: 'history',
    icon: History,
    categoryTitle: 'Operations & Automation',
    description: 'Execution logs, undo timeline, and purge records',
    keywords: ['logs', 'timeline', 'audit trail', 'undo', 'activity'],
  },

  // General Preferences
  {
    id: 'tool-settings',
    label: 'Settings',
    path: '/settings',
    icon: Settings,
    categoryTitle: 'General',
    description: 'Preferences, colour mode, thresholds, and triggers',
    keywords: ['config', 'theme', 'dark mode', 'preferences'],
  },
  {
    id: 'tool-about',
    label: 'About',
    path: '/about',
    icon: Info,
    categoryTitle: 'General',
    description: 'Version specifications, release notes, and architecture',
    keywords: ['version', 'build', 'specs', 'credits'],
  },
]

/**
 * Get route info by pathname
 */
export function getRouteInfo(pathname) {
  const cleanPath = pathname === '/' ? '/dashboard' : pathname
  const hub = PRIMARY_HUBS.find((h) => h.path === cleanPath)
  if (hub) return hub

  const tool = ALL_TOOLS.find((t) => t.path === cleanPath)
  if (tool) return tool

  return {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    icon: Home,
    faIcon: faGaugeHigh,
    categoryTitle: 'Core',
    description: 'Drive overview and storage telemetry',
  }
}
